[package]
name = "gox-vm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Custom virtual machine runtime for GoX"

[dependencies]
gox-common = { path = "../gox-common" }

[dev-dependencies]
